In [1]:
import pandas as pd

In [8]:
user_features = pd.read_csv('user_features.csv',low_memory=False)

In [9]:
len(user_features)

8264276

In [4]:
df.head()

   node_id  f1  f2  f3  f4  f5  f6  f7  f8  f9  f10  f11  f12  f13
0        2  14  14  14  12  12  12   7   7   7    0    0    0   15
1        3  31   9   7  31  16  12  31  15  12   31   15   12    8
2        4   0   0   0   0   0   0   0   0   0    0    0    0    7
3        5  31   4   1  31   7   1  31   9   1   31    9    0   15
4        6  31  27  20  31  24  14  31  20  10   31   20    5    7

In [5]:
connections = pd.read_csv('train.csv',low_memory=False)

In [6]:
len(connections)

70661802

In [7]:
connections[connections['is_chat']==1]

          node1_id  node2_id  is_chat
7          7159649   7791327        1
19         4771042    998845        1
59         3079025   3410678        1
82         3651503   3656309        1
93         6434643   1107217        1
114        4481921    504660        1
135        8531387   8136174        1
150         639430   4249041        1
153        2894527   5343816        1
214        2095286      7346        1
215        6698073    847441        1
241        3556637   8146138        1
359        6220920    382259        1
437        7434742   4745437        1
457        2753836   6226521        1
464        7183585   5197762        1
503         765389   7064940        1
518        7713243   2602438        1
666        7174297   8306215        1
765        5810780   3092643        1
869         244057   7322864        1
881        8541025   7516043        1
887        3846494   1090817        1
959        8449148   1342972        1
1096       8125824   7121924        1
1124       5512357   2845170        1
1171       1009864    720502        1
1196       4783622   4472691        1
1197       8061187   3933680        1
1209       7431218   2213813        1
...            ...       ...      ...
70660895   5432689   8324935        1
70660949   6364181   3337384        1
70660952   3719568   2767155        1
70660957   6223081    394642        1
70660972   6259896    382305        1
70660981   5329294   7423102        1
70661014   2088781   2192201        1
70661035   5427480    669541        1
70661077   4675974   4819070        1
70661080   4486483    483433        1
70661182   2190924   5000819        1
70661289   2763900   6721995        1
70661302   1093755   7824474        1
70661303   6276095   4965162        1
70661308   2354355   8166703        1
70661352   6104138   2921831        1
70661438   5092806   1092064        1
70661469   4796911   7816084        1
70661524    475997   6993989        1
70661533   2819072   1379958        1
70661557   3326335   6611719        1
70661567   6215119   1903834        1
70661570   1337399   7173787        1
70661595   8104656   8006787        1
70661686   5544870   6527299        1
70661712   4959308   4454943        1
70661723   2904947   3825352        1
70661724   4443131   2260180        1
70661731   5081295   1503071        1
70661801   5818323   1098949        1

[2251784 rows x 3 columns]

In [10]:
connections_new = connections[0:100000]

In [11]:
connections_new.head()

   node1_id  node2_id  is_chat
0   8446602   6636127        0
1   1430102   7433949        0
2   2803017   8372333        0
3   4529348    894645        0
4   5096572   4211638        0

In [13]:
len(connections_new)

100000

In [14]:
connections_new.join(user_features,on='node1_id')

,node1_id,node2_id,is_chat,node_id,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13
0,8446602,6636127,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1430102,7433949,0,1522142.0,30.0,6.0,0.0,31.0,8.0,0.0,31.0,10.0,0.0,31.0,10.0,0.0,15.0
2,2803017,8372333,0,3004873.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
3,4529348,894645,0,4853564.0,31.0,7.0,0.0,31.0,5.0,0.0,31.0,6.0,0.0,31.0,6.0,0.0,15.0
4,5096572,4211638,0,5469382.0,6.0,1.0,0.0,13.0,5.0,0.0,19.0,6.0,0.0,26.0,6.0,0.0,15.0
5,8325853,1305287,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7218175,120961,0,7743674.0,31.0,5.0,0.0,31.0,7.0,0.0,31.0,6.0,0.0,31.0,10.0,0.0,15.0
7,7159649,7791327,1,7680382.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,15.0
8,4481049,7514725,0,4804554.0,3.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
9,2232007,4102278,0,2390677.0,27.0,5.0,4.0,20.0,5.0,4.0,14.0,5.0,4.0,7.0,3.0,3.0,15.0
10,5959148,750479,0,6394095.0,23.0,19.0,4.0,29.0,24.0,10.0,29.0,23.0,12.0,27.0,22.0,15.0,15.0
11,321786,2806279,0,340128.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,8.0,8.0,1.0,15.0
12,4220897,7257701,0,4526146.0,31.0,18.0,0.0,25.0,17.0,0.0,19.0,12.0,0.0,12.0,8.0,0.0,15.0
13,6696379,6883782,0,7184810.0,26.0,15.0,1.0,31.0,18.0,1.0,31.0,18.0,1.0,31.0,17.0,3.0,7.0
14,3233784,5549279,0,3466720.0,3.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
15,1143595,3096748,0,1217055.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
16,2762740,609777,0,2963430.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,15.0
17,8308507,4485604,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2489784,3066726,0,2672494.0,31.0,3.0,0.0,31.0,3.0,0.0,31.0,2.0,0.0,31.0,2.0,0.0,15.0
19,4771042,998845,1,5113502.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,5.0
20,380641,757768,0,399054.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
21,3728724,3302160,0,3991558.0,15.0,1.0,0.0,22.0,1.0,0.0,27.0,1.0,0.0,30.0,4.0,0.0,7.0
22,8028135,2448961,0,8607964.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,15.0
23,4477060,2434301,0,4800562.0,31.0,24.0,7.0,31.0,25.0,9.0,31.0,27.0,12.0,31.0,28.0,14.0,15.0
24,180331,5558843,0,192519.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,15.0
25,2791317,8187030,0,2992877.0,31.0,28.0,22.0,31.0,29.0,23.0,31.0,30.0,23.0,31.0,31.0,22.0,15.0
26,4755157,2879663,0,5097300.0,31.0,0.0,0.0,31.0,0.0,0.0,31.0,0.0,0.0,31.0,1.0,0.0,15.0
27,5814800,1907505,0,6242297.0,31.0,17.0,2.0,31.0,21.0,6.0,31.0,23.0,7.0,31.0,28.0,14.0,15.0
28,2087636,1131367,0,2236067.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
29,8522620,2806611,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,8180815,1745822,0,8779583.0,31.0,2.0,0.0,31.0,2.0,0.0,31.0,1.0,0.0,31.0,1.0,0.0,15.0
99971,6968947,2707991,1,7470795.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
99972,367140,367140,0,385544.0,31.0,16.0,0.0,31.0,17.0,0.0,31.0,19.0,0.0,29.0,19.0,0.0,8.0
99973,4861238,3328340,0,5214087.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,15.0
99974,5893768,8009500,0,6324728.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
99975,7528407,803367,0,8077964.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
99976,1358394,8361247,0,1444235.0,21.0,21.0,20.0,14.0,14.0,14.0,8.0,8.0,8.0,3.0,3.0,3.0,15.0
99977,3083744,2903465,0,3303473.0,31.0,0.0,0.0,31.0,0.0,0.0,31.0,0.0,0.0,31.0,0.0,0.0,7.0
99978,8350273,1085673,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99979,2173270,3881654,0,2328124.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2.0,0.0,15.0
99980,2988017,5343492,0,3201526.0,31.0,1.0,0.0,31.0,1.0,0.0,31.0,1.0,0.0,31.0,1.0,0.0,15.0
99981,4202668,6225106,0,4507730.0,31.0,1.0,0.0,31.0,1.0,0.0,31.0,1.0,0.0,31.0,2.0,0.0,15.0
99982,1222441,2346290,0,1301887.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
99983,5969793,7895580,0,6405701.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
99984,7224434,3626400,0,7750163.0,8.0,8.0,6.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
99985,8445582,2755056,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99986,348652,943231,0,367006.0,28.0,1.0,0.0,29.0,1.0,0.0,31.0,1.0,0.0,31.0,2.0,0.0,15.0
99987,6957552,6605503,0,7458943.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,15.0
99988,254617,1209594,0,268061.0,25.0,20.0,1.0,18.0,17.0,1.0,12.0,12.0,1.0,5.0,5.0,1.0,10.0
99989,7508839,4125345,0,8058384.0,31.0,2.0,0.0,31.0,1.0,0.0,31.0,1.0,0.0,31.0,2.0,0.0,7.0
99990,8326183,4916785,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99991,3327184,2432018,0,3571433.0,31.0,27.0,3.0,31.0,25.0,2.0,31.0,24.0,3.0,31.0,20.0,2.0,7.0
99992,1254367,4828762,0,1333866.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,15.0
99993,1906199,6787601,0,2041279.0,31.0,14.0,0.0,31.0,12.0,0.0,31.0,12.0,0.0,31.0,14.0,0.0,15.0
99994,398828,7207158,0,417542.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
99995,325021,8131510,0,343365.0,29.0,0.0,0.0,31.0,0.0,0.0,31.0,0.0,0.0,31.0,0.0,0.0,15.0
99996,7791330,890690,0,8353151.0,31.0,4.0,0.0,31.0,3.0,0.0,31.0,2.0,0.0,31.0,2.0,0.0,15.0
99997,8046833,3639656,0,8627779.0,31.0,14.0,0.0,31.0,18.0,3.0,31.0,18.0,4.0,31.0,21.0,8.0,8.0
99998,2881987,8321648,0,3089284.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
99999,3870643,3093684,0,4145540.0,22.0,1.0,0.0,25.0,1.0,0.0,28.0,1.0,0.0,29.0,1.0,0.0,15.0

In [16]:
df_merged_sample = pd.merge(connections_new, user_features, how='left', left_on=['node1_id'], right_on=['node_id'])

In [ ]:
df_merged_sam